//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odontogram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odontogram()
        {
            this.Teeth = new HashSet<Teeth>();
        }
    
        public int Id_Odontogram { get; set; }
        public string Fk_IdPatient { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> first { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teeth> Teeth { get; set; }
    }
}
