//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Odontogram = new HashSet<Odontogram>();
        }
    
        public string Id_patient { get; set; }
        public string DocumentType { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string SecondSurname { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Occupation { get; set; }
        public string CivilState { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public string Cellphone { get; set; }
        public string Mail { get; set; }
        public string SocialSecurity { get; set; }
        public string Eps { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odontogram> Odontogram { get; set; }
    }
}
