//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdontogramAction
    {
        public int Id_action { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string shorcut { get; set; }
        public Nullable<int> type { get; set; }
    }
}
