//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teeth
    {
        public int Id_Teeth { get; set; }
        public int Id_Odontogram { get; set; }
        public Nullable<int> UpperCervical { get; set; }
        public Nullable<int> Vestibular { get; set; }
        public Nullable<int> Oclusal { get; set; }
        public Nullable<int> Palatino { get; set; }
        public Nullable<int> Distal { get; set; }
        public Nullable<int> Mesial { get; set; }
        public Nullable<int> LowerServical { get; set; }
        public Nullable<int> General { get; set; }
    
        public virtual Odontogram Odontogram { get; set; }
    }
}
